### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by ghost** [falkirks/mcpeme#1]
Can you please help me install, it says Killed

**Comment by falkirks** [comment]
What steps did you go about to install it? I will write some instructions in the README.

**Comment by ghost** [comment]
git clone https://github.com/Falkirks/mcpeme.git
cd mcpeme
npm install

Then it said Killed half way through

**Comment by falkirks** [comment]
Did it say why or just killed? What server are you running it on? Is it a VPS?

**Comment by ghost** [comment]
I was running a DigitalOcean VPS 5$ plan. It just said killed

**Comment by falkirks** [comment]
Oh, so what I think happened was it ran out of memory. You can configure swap so that doesn't happen. Digitalocean has tutorials online for various operating systems, a quick search should find one.

**Comment by ghost** [comment]
Okay. Could you give me the steps directly.

So git clone https://github.com/Falkirks/mcpeme.git
cd mcpeme
npm install
node server.js

Is that correct?

**Comment by falkirks** [comment]
Should be `npm start` I think. Also you will need to configure all the environment variables and set up a Mongo database.

**Comment by NFGamerMC** [comment]
Thanks, what are the Environment Variables? MCPE_HOME? CFLARE_PASSWORD?

**Comment by ghost** [comment]
@Falkirks How do I import the CDATA

**Comment by falkirks** [comment]
You can configure the environment using the files in config/env. Or the following environment variables (this is what I have).

```
CLOUDFLARE_DOMAIN
CLOUDFLARE_EMAIL
CLOUDFLARE_KEY
CLOUDFLARE_ZONEID
FACEBOOK_ID
FACEBOOK_SECRET
GITHUB_ID
GITHUB_SECRET
MAILER_EMAIL_ID
MAILER_FROM
MAILER_PASSWORD
MAILER_SERVICE_PROVIDER
TWITTER_KEY
TWITTER_SECRET
MONGOLAB_URI
```

the mail stuff is configured using nodemailer.
the mongolab_uri can just be the uri of a mongo database. if your database is on localhost, you don't need to set it, it will happen automatically.
all the social stuff is optional (github, twitter, facebook), it is just used for social login.

**Comment by ghost** [comment]
Thanks, also I don't know if you got my email but I do not have or use Twitter and I was wondering if he has Discord, G+, Skype, or a forums.pmmp.io account?

**Comment by falkirks** [comment]
He doesn't have any of those (except maybe a forums account). I would suggest creating a throwaway Twitter account and contacting him.

**Comment by ghost** [comment]
> @ start /root/mcpeme
> node server.js

sh: 1: node: not found

npm ERR! Linux 4.4.0-78-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `node server.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @ start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/mcpeme/npm-debug.log

**Comment by falkirks** [comment]
So you haven't installed node properly?
